import { createHmac, randomInt, timingSafeEqual } from "node:crypto";

/**
 * The hand-over code (PRD §45–46, Phase 7).
 *
 * Pure and clock-free, like `rules.ts`: this module knows how a code is made,
 * stored and compared, and nothing about Prisma or requests. The service layer
 * owns transactions and the clock.
 *
 * The code is the only thing that releases payment for the goods, so it is
 * treated as a credential:
 * - it is generated by the server with a CSPRNG, never derived from the order;
 * - only its HMAC is stored, so a database dump cannot be read out and used;
 * - comparison is timing-safe;
 * - it expires, and it locks after a handful of wrong tries.
 */

/** Six digits: long enough to be safe for one short window, short enough to read aloud. */
export const OTP_LENGTH = 6;

/**
 * How long a code stays usable.
 *
 * Platform policy, not a campus setting: the code exists for the moment two
 * people are standing together, and a campus lengthening it would weaken the one
 * control that stands between an agent and someone else's payment. The window a
 * campus *can* tune is how long the student then has to pay
 * (`goodsPaymentWindowMinutes`).
 */
export const OTP_VALIDITY_MINUTES = 20;

/**
 * Wrong tries allowed before the code is dead and the student must issue a new
 * one. Guessing six digits needs ~500k tries on average; five closes that door
 * without punishing a student who misreads their own screen.
 */
export const MAX_OTP_ATTEMPTS = 5;

/** A fresh code. Uniform over 000000–999999, including leading zeros. */
export function generateHandoverCode(): string {
  return String(randomInt(0, 10 ** OTP_LENGTH)).padStart(OTP_LENGTH, "0");
}

/** Digits only, so "482 917" typed by a human matches "482917". */
export function normaliseHandoverCode(input: string): string {
  return input.replace(/\D/g, "");
}

export function isWellFormedHandoverCode(input: string): boolean {
  return new RegExp(`^\\d{${OTP_LENGTH}}$`).test(input);
}

/**
 * What is stored for a code.
 *
 * Bound to the delivery id as well as the secret, so a hash lifted from one
 * delivery cannot be replayed against another.
 */
export function hashHandoverCode(input: {
  code: string;
  deliveryId: string;
  secret: string;
}): string {
  return createHmac("sha256", input.secret)
    .update(`${input.deliveryId}:${normaliseHandoverCode(input.code)}`)
    .digest("hex");
}

/** Timing-safe comparison of two hex digests. */
export function hashesMatch(a: string, b: string): boolean {
  const left = Buffer.from(a, "hex");
  const right = Buffer.from(b, "hex");
  if (left.length !== right.length || left.length === 0) return false;
  return timingSafeEqual(left, right);
}

export type OtpState = {
  hash: string | null;
  expiresAt: Date | null;
  attemptCount: number;
  verifiedAt: Date | null;
};

export type OtpCheck =
  | { ok: true }
  | { ok: false; reason: "NOT_ISSUED" | "ALREADY_VERIFIED" | "EXPIRED" | "LOCKED" };

/**
 * Whether a stored code may still be tried at all, before the digits are even
 * looked at. Separated from the comparison so the service can answer "ask the
 * student for a new code" without leaking whether the digits were close.
 */
export function checkOtpUsable(state: OtpState, now: Date): OtpCheck {
  if (state.verifiedAt) return { ok: false, reason: "ALREADY_VERIFIED" };
  if (!state.hash) return { ok: false, reason: "NOT_ISSUED" };
  if (state.attemptCount >= MAX_OTP_ATTEMPTS) return { ok: false, reason: "LOCKED" };
  if (state.expiresAt && state.expiresAt.getTime() <= now.getTime()) {
    return { ok: false, reason: "EXPIRED" };
  }
  return { ok: true };
}

/** Tries left, for the message the agent sees. Never negative. */
export function attemptsRemaining(attemptCount: number): number {
  return Math.max(0, MAX_OTP_ATTEMPTS - attemptCount);
}
