import { z } from "zod";

/**
 * Payment request schemas (Phase 8).
 *
 * Note what is absent: an amount. A client states *what* it wants to pay for,
 * never how much — the figure comes from the order the server wrote at checkout
 * (Rule 1). These schemas exist to reject anything else.
 */

export const deliveryFeePaymentSchema = z.object({
  orderId: z.string().min(1, "An order is required"),
});

export const goodsPaymentSchema = z.object({
  deliveryId: z.string().min(1, "A delivery is required"),
});

/** Our own reference format, as generated by `lib/payments/paystack`. */
export const paymentReferenceSchema = z
  .string()
  .trim()
  .regex(/^CM-(DF|GD)-[0-9A-F]{12}$/, "That is not a valid payment reference");

export type DeliveryFeePaymentInput = z.infer<typeof deliveryFeePaymentSchema>;
export type GoodsPaymentInput = z.infer<typeof goodsPaymentSchema>;
